### ISSUE TITLE
Make connectivity always work

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1]
Tailscale end-to-end connectivity between peers needs to always work, even if the peers have challenging/changing network configurations.

Some high level dependent bugs are:

- [x] [Finish, deploy DERP](https://github.com/tailscale/tailscale/issues/2), Issue #2 (the fallback cloud proxy for routing encrypted Wireguard packets if all else fails or when a route hasn't yet been created/found through NAT)
- [ ] [Handle more types of NATs](https://github.com/tailscale/tailscale/issues/3), Issue #3 
- [x] [Actively adapt to changing network configurations better](https://github.com/tailscale/tailscale/issues/4), Issue #4 
- [x] [IPv6 support for peer-to-peer connections](https://github.com/tailscale/tailscale/issues/18), Issue #18
- [ ] [PMTU discovery](https://github.com/tailscale/tailscale/issues/311), issue #311

/cc @danderson @apenwarr @crawshaw

**Comment by evliu** [comment]
Would this cover the scenario where you are connected to another VPN provider like NordVPN?

**Comment by bradfitz** [comment]
@evliu, this is a meta bug about connectivity in general.

There's no reason Tailscale shouldn't work alongside a default route VPN. If you encounter problems, file a separate bug with details?
