### ISSUE TITLE
Kubernetes operator egress proxies HA (multiple replicas) tracking issue

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#13406]
### What are you trying to do?

Tracking issue for Kubernetes operator egress proxy HA:

- make it possible to expose an egress service on multiple active replicas (no downtime)

- make it possible to expose many egress services on fewer proxy nodes

Design https://docs.google.com/document/d/1XQCaD2uTzeqEfOMgdxgGVsVOsRc7ojwtxheeOrSPwis/edit?usp=sharing (public doc, comments and questions are welcome)

### Prerequisites

Work to implement `ProxyGroup`

## Steps

- [x] add functionality to iptables/nftables to set up portmapping rules https://github.com/tailscale/tailscale/pull/13531
- [x] add functionality to iptables/nftables/containerboot to update a set of portmapping rules (given a config and pre-existing rules, ensure that rules no longer present in config are removed and new ones applied) https://github.com/tailscale/tailscale/pull/13531
- [x] add functionality to containerboot to dynamically reload service config and call iptables/nftables to update portmapping rules
- [x] add functionality to operator to parse egress Services for a ProxyGroup, configure proxy group to expose/unexpose egress service and ensure cluster traffic routing to ready proxy endpoints https://github.com/tailscale/tailscale/pull/13531
- [x] add Ready condition to egress Services once ready to route traffic
- [x] apply default ProxyClass to ProxyGroup resources
- [x] support dual stack clusters
- [ ] support IPv6 only clusters
- [ ] delete SNAT rules for removed egress services
- [ ] deal with scenarios where a `tailscale.com/proxy-group` annotation is added to/removed from an _existing_ Tailscale egress Service
- [ ] investigate more rapid endpoints update during Pod re-creation (proxies themselves could update the EndpointSlice?)

Related https://github.com/tailscale/tailscale/issues/10102

**Comment by irbekrm** [comment]
There is now an initial unstable release available that implements this.
This is `1.75.89` [Tailscale Kubernetes operator 'unstable' Helm chart](https://tailscale.com/kb/1236/kubernetes-operator#helm:~:text=The%20https%3A//pkgs.tailscale.com/unstable/helmcharts%20repository%20contains%20charts%20with%20the%20very%20latest%20changes%2C%20published%20in%20between%20official%20releases.) (or `unstable-v1.75.89` operator and proxy image versions + [latest static manifests from Tailscale GitHub repo](https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/manifests/operator.yaml))

### To try this out:

1. Create a `ProxyGroup` custom resource:
```
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress-proxies
spec:
  type: egress
  replicas: 3
```
The above manifest will create a `StatefulSet` with 3 replicas, each a Tailscale device.
See [API docs](https://github.com/tailscale/tailscale/blob/main/k8s-operator/api.md#proxygroupspec) for full custom resource spec.

2. Create a [Tailscale egress `Service`](https://tailscale.com/kb/1438/kubernetes-operator-cluster-egress) with
`tailscale.com/proxy-group` annotation pointing to `egress-proxies` `ProxyGroup` and with ports that you want to access on the egress service:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/proxy-group: egress-proxies
    tailscale.com/tailnet-fqdn: my-ts-service.tailxyz.ts.net
  name: my-ts-service
  namespace: default
spec:
  externalName: placeholder
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
  type: ExternalName
```
It will take up to a minute for the service to become ready. Once it has, the cluster workloads can access the tailnet service via the `my-ts-service` as normally, i.e `curl my-ts-service.default:8080` etc.
Note that unlike with the single-proxy egress `Service`s you _must_ specify all the ports you want to access on the tailnet service.
You can expose any number (restricted by resource consumption) of egress services on a `ProxyGroup` replicas.

### Debugging

There is a ClusterIP `Service` with a custom `EndpointSlice` managed by the operator created for each egress service in the operator's namespace.
Once proxy `Pod`s have updated their configuration to route cluster traffic to the tailnet service, the `EndpointSlice` will have their IP addresses. Once the `EndpointSlice` has at least one proxy `Pod` endpoint, the traffic can be routed. You can verify this:
```
$ kubectl get endpointslice -n tailscale -l tailscale.com/parent-resource=<my-ts-service>
```
### Limitations/caveats that we know of and are working to fix:

- IPv6-only clusters are not yet supported
- There is no mechanism to migrate existing single-replica proxies to the new mechanism. If you add a `tailscale.com/proxy-group` annotation to an existing Tailscale egress `Service` that's already exposed via the single-proxy-replica mechanism, it will get exposed on the `ProxyGroup` however the cluster resources for the single replica mechanism will remain dangling
- [default `ProxyClass`](https://github.com/tailscale/tailscale/blob/866714a8941072ce576628d62b8cd0eed3f67e3e/cmd/k8s-operator/deploy/chart/values.yaml#L84) will currently not get applied to `ProxyGroup` cluster resources
- currently exposing a new service relies on a `ConfigMap` mounted to the proxy `Pod`s getting updated- in practice this means that it will take up to a minute for a new service to become ready
- currently there is no user friendly way (i.e a `Service` condition) to observe when the service is ready

Feedback and suggestions are very welcome 🙏🏼

**Comment by olleman42** [comment]
We have attempted to use `ProxyGroup`s for egress services in our cluster with some success; however, we have a question regarding the viability of using `targetPort` when defining the `ExternalName` service.

Our understanding is that the operator utilizes the port property to configure the port mapping between the proxy pods and the service that the operator manages, effectively ignoring the targetPort property in the original service definition. There is no mention of this in the documentation, and the property is also absent from the service definition example.

Is there a specific reason for not mapping the targetPort on the receiving end (between the proxy and the target tailnet service), or for not using some other mechanism to retain the additional port mapping functionality (as it does in the non-ProxyGroup implementation)?

We have multiple services exposed via egress services that we would like to expose through ProxyGroups for their high availability aspects. However, we are now forced to either reconfigure the ports called by the applications or add another translation layer between our workloads and the services we define (which the operator then acts upon).

**Comment by irbekrm** [comment]
@olleman42 thank you for taking a look at the `ProxyGroup`.

Could you give an example of what you want to do with the `targetPort` /what workflow yo are aimig for/how are you configuring it now?

As you say `spec.ports` need to be defined on the ExternalName `Service`s for `ProxyGroup` just for the operator to be able to create an additional portmapping layer behind the scenes - so the same port for _multiple_ tailnet services can be exposed via the same `ProxyGroup`. 

Our intention was to make it so that users _only_ have to configure/care about one port, in this case the port that is exposed on the tailnet service.

So the full flow would be:
1. You have a tailnet service `my-ts-service.tailxyz.ts.net` that listens on port 8080
2. You create an ExternalName Service:
```
apiVersion: v1
kind: Service
metadata:
  name: my-ts-service
  namespace: default
  annotations:
    tailscale.com/proxy-group: egress-proxies
    tailscale.com/tailnet-fqdn: my-ts-service.tailxyz.ts.net
spec:
  ports:
  - port: 8080
```
3. The operator behind the scenes ensures that _cluster_ traffic sent to `my-ts-service.default.cluster.local:8080` is routed to to tailnet target `my-ts-service.tailxyz.ts.net:8080`. (For this we actually map to another port on ProxyGroup proxies to ensure that multiple tailnet services can expose port 8080 via one `ProxyGroup` - but this is hidden from users)

4. Your apps can then access `my-ts-service.tailxyz.ts.net:8080` by calling `my-ts-service.default.svc.cluster.local:8080`

What we were aiming for is:
- users only need to configure the port(s) that need to be accessed on the tailnet service
- multiple ExternalName `Service`s can expose the same port for different tailnet targets via a single `ProxyGroup`
- applications can refer to the tailnet service by the actual port that it exposes and don't need to be aware of any other ports

**Comment by dnmgns** [comment]
The design-proposal as well as the documentation seems to suggest that it should be possible to specify multiple ports for an egress service. The design proposal leaves out `name` for the ports, which is a requirement for a svc. And the documentation doesn't specify how to add multiple ports, just that it can be done.

Here's an example of what I would expect to be possible:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: example-worker-1.tailabc00.ts.net.
    tailscale.com/proxy-group: tailscale-operator-proxygroup-egress
    no-ingress: true
  name: example-worker-1
spec:
  externalName: placeholder-will-be-overwritten-by-operator
  type: ExternalName
  ports:
    - name: webservice
      port: 3000
    - name: proxy
      port: 1080
```

In turn, this seems to generate the following svc:
```
$ k get svc ts-example-worker-1-bc974 -n tailscale-operator -o yaml

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-10-18T13:57:51Z"
  generateName: ts-example-worker-1-
  labels:
    tailscale.com/managed: "true"
    tailscale.com/parent-resource: example-worker-1
    tailscale.com/parent-resource-ns: example
    tailscale.com/parent-resource-type: svc
    tailscale.com/proxy-group: tailscale-operator-proxygroup-egress
    tailscale.com/svc-type: egress
  name: ts-example-worker-1-bc974
  namespace: tailscale-operator
  resourceVersion: "2787607766"
  uid: a14e39ae-e861-44b5-b3ab-2c62886223d1
spec:
  clusterIP: 172.20.7.60
  clusterIPs:
  - 172.20.7.60
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 9332
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

Specifying multiple port definitions results in `externalName` not being updated, and the operator throwns an error:
```
[operator-c5cd855d5-2twhh] {"level":"error","ts":"2024-11-28T09:53:50Z","msg":"Reconciler error","controller":"egress-svcs-reconciler","namespace":"example","name":"example-worker-1","reconcileID":"78531dba-e261-44c1-8f6d-f3810320a9b6","error":"error ensuring ClusterIP Service: Service \"ts-example-worker-1-bc974\" is invalid: spec.ports[0].name: Required value","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}
```

So the operator seems to generate a new service in the tailscale-operator namespace, lacking a `spec.ports[0].name` even though it's specified in the egress service.

Am I missing something or is this is a bug? Let me know in case you'd like me to open a separate issue for this.

**Comment by irbekrm** [comment]
Hi @dnmgns 

It should work with multiple ports and the `Service` spec should be exactly like in your example with a name for each of the different ports (we should actually update our docs, as you say).

The error seems to come from where we are creating another `ClusterIP` `Service` - the operator should have at this point picked the port name from the `ExternalName` `Service` (see [here](https://github.com/tailscale/tailscale/blob/61dd2662eca775c8a3f6700a0194db5816de5049/cmd/k8s-operator/egress-services.go#L258)) that you created, but looks like something has gone wrong.

I just tried to reproduce this with your exact example, but wasn't able to (it worked fine for me).
What version are you running? Also, any other tips for how to reproduce would be appreciated.

**Comment by dnmgns** [comment]
> Actually, I can reproduce the issue if I:
> 
>     1. create a Service with just one port without name:
> 
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   annotations:
>     tailscale.com/tailnet-fqdn: example-worker-1.tailabc00.ts.net.
>     tailscale.com/proxy-group: tailscale-operator-proxygroup-egress
>     no-ingress: true
>   name: example-worker-1
> spec:
>   externalName: placeholder-will-be-overwritten-by-operator
>   type: ExternalName
>   ports:
>   - port: 3000
> ```
> 
>     2. update that Service to add a second named port + a name for the first port:
> 
> 
> ```
> apiVersion: v1
> kind: Service
> metadata:
>   annotations:
>     tailscale.com/tailnet-fqdn: example-worker-1.tailabc00.ts.net.
>     tailscale.com/proxy-group: tailscale-operator-proxygroup-egress
>     no-ingress: true
>   name: example-worker-1
> spec:
>   externalName: placeholder-will-be-overwritten-by-operator
>   type: ExternalName
>   ports:
>    - name: webservice
>       port: 3000
>     - name: proxy
>       port: 1080
> ```
> 
> We should obviously fix this, but I assume that if you delete and recreate the `Service` like in your example it would work for you?

This is our _exact_ scenario. We haven't actually tried with recreating the service, so that's a very valuable insight and provides the best workaround so far. Thanks! (For the record; we're on 1.76.7)

**Comment by irbekrm** [comment]
> This is our exact scenario. We haven't actually tried with recreating the service, so that's a very valuable insight and provides the best workaround so far. Thanks! (For the record; we're on 1.76.7)

Thank you for confirming!
https://github.com/tailscale/tailscale/pull/14247 should hopefully fix this bug

**Comment by irbekrm** [comment]
@dnmgns we've merged a fix and published a dev release with the fix (`1.77.153` 'dev' Kubernetes operator Helm chart or `unstable-1.77.153` image if using static manifests). 
It should come out in a stable release towards the end of next week.

**Comment by dnmgns** [comment]
> @dnmgns we've merged a fix and published a dev release with the fix (`1.77.153` 'dev' Kubernetes operator Helm chart or `unstable-1.77.153` image if using static manifests). 
> 
> It should come out in a stable release towards the end of next week.

Fantastic, thanks for the update! I’ll check out the dev release (1.77.153) and give it a try. Looking forward to the stable release next week!

**Comment by mpstefan** [comment]
Closed in favor of individual issues so we can prioritize these things separately.
