### ISSUE TITLE
VM-based Integration testing

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#1988]
This will spawn up a bunch of virtual machines, test Tailscale features on them and then tell us which distros work and which fail.

- [x] base implementation in #1966
- [x] figure out a good bindhost for testcontrol
- [x] glue between io.Writer and t.Logf (#2007)
- [x] test with locally built binaries (#2006)
- [x] maintain distro name in the myIP handler (#2020)
- [x] investigate distro name-based globbing or regex matching (#2021)
- [x] do tests as machines register with testcontrol rather than waiting for all of them to register (#2022)
- [x] add a semaphore to limit ram use (#2022)
- [x] download test images from S3 (#2035)
- [x] easy way to download all of the images at once (#2039)
- [x] figure out a home for the VM tests (#2044)
- [x] aggressively verify images and redownload if the checksum doesn't match (#2050)

Stretch goals/nice-to-haves:
- [x] figure out why OpenSUSE 15.1 images are broken (#2038)
- [x] run tests on obscure distros like Arch/Alpine
  - [x] Arch (#2040)
  - [x] Alpine (#2098)
- [x] only build binaries once (#2042)
- [x] spew qemu output to test logs (#2047)
- [ ] serve seed metadata over HTTP instead of as an ISO file
- [ ] add "fast" mode that only tests the most recent release of each distro

**Comment by bradfitz** [comment]
I remembered another thing that VM-based tests aren't doing correctly:

We should never hit the external network to fetch URLs or binaries: https://github.com/tailscale/tailscale/blob/d2c4e75099f512ef438e84fac086ce7b0c29e9de/tstest/integration/vms/vms_test.go#L486

Instead, it should use the `tailscale` and `tailscaled` binary as built by the test parent already:

https://github.com/tailscale/tailscale/blob/d2c4e75099f512ef438e84fac086ce7b0c29e9de/tstest/integration/integration_test.go#L238

Ideally we'd also built the deb/rpm/apk/etc in the test and use that, but in the meantime we can just copy the two binaries into the right places (and maybe a systemd unit too, which fortunately is already in the tree: https://github.com/tailscale/tailscale/blob/d2c4e75099f512ef438e84fac086ce7b0c29e9de/cmd/tailscaled/tailscaled.service along with the defaults file)

**Comment by DentonGentry** [comment]
I think this is as done as the current iteration is going to get. Further work on integration tests is being tracked elsewhere.
